resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

jobs:
- job: Linux
  pool: Hosted Ubuntu 1604

  steps:
  - script: |
      wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
      sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.1.92-xenial.list http://packages.lunarg.com/vulkan/1.1.92/lunarg-vulkan-1.1.92-xenial.list
      sudo apt update
      sudo apt install lunarg-vulkan-sdk
      sudo apt-get -y install freeglut3 freeglut3-dev
      sudo apt-get -y install xorg-dev libglu1-mesa-dev
    displayName: 'Command Line Script'

  - task: CMake@1
    displayName: 'Generating Project Files'
    inputs:
      cmakeArgs: 'cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ../'


  - task: CMake@1
    displayName: 'Building OpenNFS'
    inputs:
      cmakeArgs: '--build ./ --target OpenNFS -- -j 4'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Linux'
    inputs:
      pathtoPublish: ./build/OpenNFS
      artifactName: Linux

- job: Windows_gcc
  pool: Hosted VS2017

  steps:
  - task: CMake@1
    displayName: 'Generating Project Files'
    inputs:
      cmakeArgs: '-G "CodeBlocks - MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Release ../'


  - task: CMake@1
    displayName: 'Building OpenNFS'
    inputs:
      cmakeArgs: '--build ./ --target OpenNFS -- -j 4'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: MinGW_Windows'
    inputs:
      pathtoPublish: ./build/OpenNFS.exe
      artifactName: MinGW_Windows

- job: Windows_msvc
  pool: Hosted VS2017

  steps:
  - script: mkdir build
    displayName: Make build directory

  - task: CMake@1
    displayName: 'Generate Solution Files'
    inputs:
      cmakeArgs: '-G "Visual Studio 15 2017 Win64" ../'


  - task: VSBuild@1
    displayName: 'Build solution OpenNFS.sln'
    inputs:
      solution: 'build/OpenNFS.sln'

      platform: 'x64'

      configuration: 'Release'


  - task: PublishSymbols@2
    displayName: 'Publish symbols path'
    inputs:
      SearchPattern: '**\bin\**\*.pdb'

      PublishSymbols: false

    continueOnError: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: './build/Release/'

      Contents: OpenNFS.exe

      TargetFolder: '$(build.artifactstagingdirectory)'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: MSVC_Windows'
    inputs:
      pathtoPublish: '$(build.artifactstagingdirectory)'
      artifactName: MSVC_Windows

- job: Mac
  pool: Hosted macOS

  steps:
  - task: CMake@1
    displayName: 'Generating Project Files'
    inputs:
      cmakeArgs: 'cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ../'


  - task: CMake@1
    displayName: 'Building OpenNFS'
    inputs:
      cmakeArgs: '--build ./ --target OpenNFS -- -j 4'


  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Mac'
    inputs:
      pathtoPublish: ./build/OpenNFS
      artifactName: Mac
