resources:
  repositories:
  - repository: self
    checkoutOptions:
      submodules: true

jobs:
- job: Linux
  pool: Hosted Ubuntu 1604

  steps:
  - script: |
      sudo apt-get -y install freeglut3 freeglut3-dev
      sudo apt-get -y install xorg-dev libglu1-mesa-dev
    displayName: 'Command Line Script'

  - task: CMake@1
    displayName: 'Generating Project Files'
    inputs:
      cmakeArgs: 'cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ../'


  - task: CMake@1
    displayName: 'Building OpenNFS'
    inputs:
      cmakeArgs: '--build ./ --target OpenNFS -- -j 4'


#  - task: PublishBuildArtifacts@1
#    displayName: 'Publish Artifact: drop'
#    inputs:
#      PathtoPublish: ./build/OpenNFS

- job: Windows_gcc
  pool: Hosted VS2017

  steps:
  - task: CMake@1
    displayName: 'Generating Project Files'
    inputs:
      cmakeArgs: '-G "CodeBlocks - MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Release ../'


  - task: CMake@1
    displayName: 'Building OpenNFS'
    inputs:
      cmakeArgs: '--build ./ --target OpenNFS -- -j 4'


#  - task: PublishBuildArtifacts@1
#    displayName: 'Publish Artifact: drop'
#    inputs:
#      PathtoPublish: ./build

- job: Windows_msvc
  pool: Hosted VS2017

  steps:
  - script: |
      git submodule init
      git submodule update --remote
    
    displayName: 'Command Line Script'
    
  - script: mkdir build
    displayName: Make build directory

  - task: CMake@1
    displayName: 'Generate Solution Files'
    inputs:
      cmakeArgs: '-G "Visual Studio 15 2017 Win64"'


  - task: VSBuild@1
    displayName: 'Build solution OpenNFS.sln'
    inputs:
      solution: 'OpenNFS.sln'

      platform: 'x64'

      configuration: 'Release'


  - task: PublishSymbols@2
    displayName: 'Publish symbols path'
    inputs:
      SearchPattern: '**\bin\**\*.pdb'

      PublishSymbols: false

    continueOnError: true

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: './Release/'

      Contents: OpenNFS.exe

      TargetFolder: '$(build.artifactstagingdirectory)'


#  - task: PublishBuildArtifacts@1
#    displayName: 'Publish Artifact: drop'
#    inputs:
#      PathtoPublish: '$(build.artifactstagingdirectory)'

- job: Mac
  pool: Hosted macOS

  steps:
  - task: CMake@1
    displayName: 'Generating Project Files'
    inputs:
      cmakeArgs: 'cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ../'


  - task: CMake@1
    displayName: 'Building OpenNFS'
    inputs:
      cmakeArgs: '--build ./ --target OpenNFS -- -j 4'


#  - task: PublishBuildArtifacts@1
#    displayName: 'Publish Artifact: drop'
#    inputs:
#      PathtoPublish: ./build/OpenNFS
