version: 2

jobs:
  build:
    docker:
      - image: ubuntu:14.04
    steps:
        # Ensure image has git
      - run: apt-get -qq update; apt-get -y install git; apt-get install wget; apt-get -y install build-essential
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'wget http://www.cmake.org/files/v3.4/cmake-3.4.1.tar.gz && tar -xvzf cmake-3.4.1.tar.gz && cd cmake-3.4.1/ && ./configure && make'
      - run:
          name: Creating Build Files
          command:
            'mkdir cmake-build-debug && cd cmake-build-debug && cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" ../'
      - run:
          name: Creating Binary Files
          command: 'cd cmake-build-debug && cmake --build ./ --target OpenNFS -- -j 4'